title: Scattering Cimarron-Tracking Cuban Physicists
baseurl: "" # dejar vacío si usas https://usuario.github.io/repositorio
url: ""     # dejar vacío para desarrollo local
baseurl: "/Tracking_Cuban_Physicists"
